flask_app/website/views.py
from flask import Blueprint, redirect, render_template, request, send_file, url_for
from werkzeug.utils import secure_filename
from sqlalchemy import exc
import requests
from requests.exceptions import HTTPError
import json
from . import db
from .models import Connectors

views = Blueprint("views", __name__)


@views.route('/')
def home():
    return render_template('home.html')


def retrieve_db_info():
    pass


@views.route('/add_connector_poc', methods=['GET', 'POST'])
def add_connector_poc():
    if request.method == 'POST':
        if request.form.get('add_connector'):
            connector_name = request.form.get('connector_name')
            connector_host = request.form.get('connector_host')
            connector_port = request.form.get('connector_port')
            create_connector = Connectors(name=connector_name, worker_host=connector_host, worker_port=connector_port)
            db.session.add(create_connector)
            try:
                db.session.commit()
            except exc.SQLAlchemyError as e:
                error = str(e.__dict__['orig'])
                return error
        elif request.form.get('cancel_action'):
            return render_template('home.html')
    return render_template('add_connector_poc.html')


@views.route('/list_connector_poc', methods=['GET', 'POST'])
def list_connector_poc():
    connector_list = Connectors.query.all()
    button_enabled = 1

    # Enable / Disable Buttons based on connector presence
    for connector in connector_list:
        host = connector.worker_host
        port = connector.worker_port
        base_url = f'http://{host}:{port}'
        try:
            print(base_url)
            res = requests.get(base_url)
            print(res.content)
            res.raise_for_status()
        except HTTPError as http_err:
            print(f'HTTP error occurred: {http_err}')
        except Exception as err:
            print(f'Other error occurred: {err}')
        except requests.ConnectionError as error:
            print(error)

    return render_template('list_connector_poc.html', connector_list=connector_list)


@views.route('/config_connector_poc')
def config_connector_poc():
    # Retrieve ID details from DB
    my_id = request.args.get('id')
    db_id = Connectors.query.get(my_id)
    db_connector_name = db_id.name
    db_connector_host = db_id.worker_host
    db_connector_port = db_id.worker_port

    try:
        base_url = f"http://{db_connector_host}:{db_connector_port}"
        print("BASE_URL", base_url)
        res = requests.get(base_url, timeout=10)
        res.raise_for_status()
        if res.status_code == 200:
            config_url = (base_url + '/connectors/' + db_connector_name + '/config')
            print("CONFIG_URL", config_url)
            res_config = requests.get(config_url)
            print("RES_CONFIG", res_config)
            res_json = res_config.json()
            print(res_json)
            with open(f'website/{db_connector_name}.json', 'w') as json_file:
                json.dump(res_json, json_file, indent=4)
                file = f'{db_connector_name}.json'
    except HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')
    except Exception as err:
        print(f'Other error occurred: {err}')

    return send_file(file, as_attachment=True)


@views.route('/pause_connector_poc')
def pause_connector_poc():
    # Retrieve ID details from DB
    my_id = request.args.get('id')
    db_id = Connectors.query.get(my_id)
    db_connector_name = db_id.name
    db_connector_host = db_id.worker_host
    db_connector_port = db_id.worker_port

    try:
        base_url = f"http://{db_connector_host}:{db_connector_port}"
        print("BASE_URL", base_url)
        res = requests.get(base_url, timeout=10)
        res.raise_for_status()
        if res.status_code == 200:
            pause_url = (base_url + "/connectors/" + db_connector_name + "/pause")
            print("PAUSE_URL", pause_url)
            requests.put(pause_url)
    except HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')
    except Exception as err:
        print(f'Other error occurred: {err}')

    return redirect(url_for('views.list_connector_poc'))


@views.route('/resume_connector_poc')
def resume_connector_poc():
    # Retrieve ID details from DB
    my_id = request.args.get('id')
    db_id = Connectors.query.get(my_id)
    db_connector_name = db_id.name
    db_connector_host = db_id.worker_host
    db_connector_port = db_id.worker_port

    try:
        base_url = f"http://{db_connector_host}:{db_connector_port}"
        print("BASE_URL", base_url)
        res = requests.get(base_url, timeout=10)
        res.raise_for_status()
        if res.status_code == 200:
            resume_url = (base_url + "/connectors/" + db_connector_name + '/resume')
            print("RESUME_URL", resume_url)
            requests.put(resume_url)
    except HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')
    except Exception as err:
        print(f'Other error occurred: {err}')

    return redirect(url_for('views.list_connector_poc'))


@views.route('/status_connector_poc')
def status_connector_poc():
    status_json = {}
    # Retrieve ID details from DB
    my_id = request.args.get('id')
    db_id = Connectors.query.get(my_id)
    db_connector_name = db_id.name
    db_connector_host = db_id.worker_host
    db_connector_port = db_id.worker_port

    try:
        base_url = f"http://{db_connector_host}:{db_connector_port}"
        # print("BASE_URL", base_url)
        res = requests.get(base_url, timeout=10)
        res.raise_for_status()
        if res.status_code == 200:
            status_url = (base_url + "/connectors/" + db_connector_name + "/status")
            connector_status = requests.get(status_url)
            status_json = connector_status.json()
            name = status_json['name']
            state = status_json['connector']['state']
            worker_id = status_json['connector']['worker_id']
            task_elements = status_json['tasks']
            return render_template('status_connector_poc.html', name=name, state=state, worker_id=worker_id,
                                   task_elements=task_elements)
    except HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')
    except Exception as err:
        print(f'Other error occurred: {err}')
    return redirect(url_for('views.list_connector_poc'))


@views.route('/update_connector_poc', methods=['POST', 'GET'])
def update_connector_poc():
    connector_id = request.args.get('id')
    if request.method == 'POST':
        f = request.files['file']
        filename = secure_filename(f.filename)
        f.save('./website/static/' + filename)
        return redirect(url_for('views.update_button', connector_id=connector_id, filename=filename))

    return render_template('update_connector_poc.html')


@views.route('update_button', methods=['POST', 'GET'])
def update_button():
    filename = request.args.get('filename')
    connector_id = request.args.get('connector_id')
    db_id = Connectors.query.get(connector_id)
    db_connector_name = db_id.name
    db_connector_host = db_id.worker_host
    db_connector_port = db_id.worker_port
    current_dir = './website/static/'
    file_path = f'{current_dir}{filename}'
    with open(file_path) as json_object:
        json_data = json.load(json_object)
    try:
        base_url = f'http://{db_connector_host}:{db_connector_port}'
        print(base_url)
        res = requests.get(base_url, timeout=10)
        res.raise_for_status()
        if res.status_code == 200:
            update_config = (base_url + '/connectors/' + db_connector_name + '/config')
            print(update_config)
            print(json_data)
            requests.put(update_config, json=json_data)
    except HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')
    except Exception as err:
        print(f'Other error occurred: {err}')

    return redirect(url_for('views.list_connector_poc'))


@views.route('delete_connector_poc')
def delete_connector_poc():
    # Retrieve ID details from DB
    my_id = request.args.get('id')
    db_id = Connectors.query.get(my_id)
    db_connector_name = db_id.name
    db_connector_host = db_id.worker_host
    db_connector_port = db_id.worker_port

    try:
        base_url = f"http://{db_connector_host}:{db_connector_port}"
        print("BASE_URL", base_url)
        res = requests.get(base_url, timeout=10)
        res.raise_for_status()
        if res.status_code == 200:
            delete_url = (base_url + "/connectors/" + db_connector_name)
            print("DELETE_URL", delete_url)
            requests.delete(delete_url)
            db_id = Connectors.query.get(my_id)
            db.session.delete(db_id)
            try:
                db.session.commit()
            except exc.SQLAlchemyError as e:
                error = str(e.__dict__['orig'])
                return error

    except HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')
    except Exception as err:
        print(f'Other error occurred: {err}')
    return redirect(url_for('views.list_connector_poc'))


@views.route('remove_fromdb')
def remove_fromdb():
    # Retrieve ID details from DB
    my_id = request.args.get('id')
    db_id = Connectors.query.get(my_id)
    db.session.delete(db_id)
    try:
        db.session.commit()
        connector_list = Connectors.query.all()
    except exc.SQLAlchemyError as e:
        error = str(e.__dict__['orig'])
        return error
    return render_template('list_connector_poc.html', connector_list=connector_list)

flask_app/website/templates/add_connector_poc.html
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>
    <nav class="navbar is-info" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Home
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" href="/add_connector_poc">
                Add Connector POC
              </a>
              <a class="navbar-item" href="/list_connector_poc">
                Connector's List POC
              </a>
            </div>
            
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
    <section class="section">
        <h1 class="title">Add connector</h1>
        <h2 class="subtitle">
          Add a new connector POC to the database
        </h2>
    </section>
    </div>
    <div class="container">

    <form method="POST">
      <div class="field">
        <label class="label">Connector's Name</label>
        <div class="control">
          <input class="input is-danger" name="connector_name" type="text" placeholder="">
        </div>
      </div>
      <p class="help is-danger">This field is required</p>

      <div class="field">
        <label class="label">Worker Host</label>
        <div class="control has-icons-left has-icons-right">
          <input class="input is-danger" name="connector_host" type="text" placeholder="" value="">
        </div>
        <p class="help is-danger">This field is required</p>
      </div>

      <div class="field">
        <label class="label">Worker Port</label>
        <div class="control has-icons-left has-icons-right">
          <input class="input is-danger" name="connector_port" type="text" placeholder="" value="">
        </div>
        <p class="help is-danger">This field is required</p>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <button type="submit" value="add" name="add_connector" class="button is-link">Submit</button>
        </div>
        <div class="control">
          <button type="submit" value="cancel" name="cancel_action" class="button is-link is-light">Cancel</button>
        </div>
      </div>
    </form>

    </div>
  </body>
</html>

flask_app/website/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>

    <nav class="navbar is-info" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Home
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" href="/add_connector_poc">
                Add Connector POC
              </a>
              <a class="navbar-item" href="/list_connector_poc">
                Connector's List POC
              </a>
            </div>

          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>

  </body>
</html>

flask_app/website/templates/list_connector_poc.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>
    <nav class="navbar is-info" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Home
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" href="/add_connector_poc">
                Add Connector POC
              </a>
              <a class="navbar-item" href="/list_connector_poc">
                Connector's List POC
              </a>
            </div>
            
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
    <section class="section">
        <h1 class="title">Connector's List</h1>
        <h2 class="subtitle">
          The List of Connectors POC
        </h2>
    </section>
    </div>
    <div class="container">

    <div class="container">
    <form method="POST">
    <div class="table-container">
        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th>Connector's Name</th>
                    <th>Worker's Host</th>
                    <th>Worker's Port</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for connector in connector_list %}
                <tr>
                    <td>{{connector.name}} <a href="{{ url_for('views.remove_fromdb', id=connector.id)}}" class="button is-danger is-light is-small">Remove from DB</a></td>
                    <td>{{connector.worker_host}}</td>
                    <td>{{connector.worker_port}}</td>
                    <td>
                      {% if button_enabled != 0 %}
                      <a href="{{ url_for('views.status_connector_poc', id=connector.id)}}" class="button is-link is-small">Status</a>
                      <a href="{{ url_for('views.pause_connector_poc', id=connector.id)}}" class="button is-warning is-small">Pause</a>
                      <a href="{{ url_for('views.resume_connector_poc', id=connector.id)}}" class="button is-success is-small">Resume</a>
                      <a href="{{ url_for('views.config_connector_poc', id=connector.id)}}" class="button is-info is-small">Config</a>
                      <a href="{{ url_for('views.update_connector_poc', id=connector.id)}}" class="button is-primary is-small">Update</a>
                      <a href="{{ url_for('views.delete_connector_poc', id=connector.id)}}" class="button is-danger is-small">Delete</a>
                      {% endif %}
                      {% if button_enabled == 0 %}
                      <button class="button is-danger is-loading">is-loading</button>
                      {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
  </form>
  </body>
</html>

flask_app/website/templates/status_connector_poc.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>
    <nav class="navbar is-info" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Home
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" href="/add_connector_poc">
                Add Connector POC
              </a>
              <a class="navbar-item" href="/list_connector_poc">
                Connector's List POC
              </a>
            </div>
            
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
    <section class="section">
        <h1 class="title">{{name}}</h1>
    </section>
    <div class="table-container">
      <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
          <thead>
              <tr>
                  <th>State</th>
                  <th>Worker ID</th>
              </tr>
          </thead>
          <tbody>
              <tr>
                  <td>{{state}}</a></td>
                  <td>{{worker_id}}</td>
              </tr>
          </tbody>
      </table>
  </div>

  <div class="table-container">
    <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <thead>
            <tr>
                <th>Tasks ID</th>
                <th>State</th>
                <th>Worker ID</th>
            </tr>
        </thead>
        <tbody>
            <tr>
              {% for item in task_elements %}
                <td>{{item.id}}</td>
                <td>{{item.state}}</td>
                <td>{{item.worker_id}}</td>
              {% endfor %}
            </tr>
        </tbody>
    </table>
</div>

    </div>
  </body>
</html>

flask_app/website/templates/update_connector_poc.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>
    <nav class="navbar is-info" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Home
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" href="/add_connector_poc">
                Add Connector POC
              </a>
              <a class="navbar-item" href="/list_connector_poc">
                Connector's List POC
              </a>
            </div>
            
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      <section class="section">
          <h1 class="title">Connector's Config Update</h1>
          <h2 class="subtitle">
            Upload a file to update the config
          </h2>
      </section>
      </div>
      <div class="container">
    
    <div class="container ">
    <form class='box' action="" method="POST" enctype="multipart/form-data">

      <div class="file is-primary">
        <label class="file-label">
          <input class="file-input" type="file" name="file">
          <span class="file-cta">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              JSON File…
            </span>
          </span>
        </label>
        <div class="pl-3">
        <button type="submit" class="button is-success">
          <span class="icon is-small">
            <i class="fas fa-check"></i>
          </span>
          <span>Update</span>
        </button>
      </div>
      </div> 

    </form>
    </div>

  </body>
</html>